Sprint 1/step 2
tachkovsa/yandex-react-burger pull request #2
Opened 2022-01-29 15:50 UTC by tachkovsa

Функционал проекта, полученный в результате работы над первым спринтом.

**Предварительно проверен по чек-листу:**
https://code.s3.yandex.net/react/checklists-pdf/checklist-1.pdf

2022-01-30 16:34 UTC, batr94 requested changes
Здравствуйте! Ваша работа выполнена на высоком уровне! Код разметки написан правильно, созданы все необходимые компоненты для работы приложения.
Весь необходимый функционал работает правильно, без ошибок при сборке проекта. Но в работе есть несколько замечаний, которые нужно исправить:

* Модальные окна не должны быть описаны в компонентах BurgerIngredients и BurgerConstructor
* В компоненте Modal, в зависимости useEffect следует добавить onClose

2022-01-30 16:34 UTC, batr94 commented on src/components/modal/modal.tsx
> +    }, []);
Надо исправить

В качестве зависимости слеудет указать onClose

2022-01-30 16:34 UTC, batr94 commented on src/components/modal/modal.tsx
> +const Modal = ({ children , header, onClose }) => {
Компоненты созданы в функциональном стиле, отлично!

2022-01-30 16:34 UTC, batr94 commented on src/components/modal/modal.tsx
> +            if (e.key === 'Escape' || e.keyCode === 27) {
Надо исправить

Числовые значения следует выносить в именованные константы, чтобы по названию константы можно было понять, что значит это число

```js
const ESC_KEYCODE = 27
```

2022-01-30 16:34 UTC, batr94 commented on src/components/burger-ingredients/burger-ingredients.tsx
> +            {modalVisible && toggledIngredient && (
Надо исправить

Компонент BurgerIngredients должен отвечать только за отображение списка ингредиентов. Он не должен отвечать за отображение модального окна ингредиента. Разметку модального окна следует перенести в компонент App

2022-01-30 16:34 UTC, batr94 commented on src/components/burger-constructor/burger-constructor.tsx
>      const [bottomBun, setBottomBun] = useState<any>(undefined);
Можно лучше

У бургера не может быть двух разных вида булок. Поэтому для хранения данных булки можно использовать только один стейт

2022-01-30 16:34 UTC, batr94 commented on src/components/burger-constructor/burger-constructor.tsx
> +            {modalVisible && orderNumber && (
Надо исправить

Компонент BurgerConstructor должен отвечать только за отображение списка ингредиентов в конструкторе. Он не должен отвечать за отображение модального окна ингредиента. Разметку модального окна следует перенести в компонент App

2022-01-30 16:55 UTC, tachkovsa commented on src/components/modal/modal.tsx
> +    }, []);
Исправлено в https://github.com/tachkovsa/yandex-react-burger/commit/d35d006031eff5920b97c4e1ea54be65ff43baec

2022-01-30 16:57 UTC, tachkovsa commented on src/components/modal/modal.tsx
> +            if (e.key === 'Escape' || e.keyCode === 27) {
Исправлено в https://github.com/tachkovsa/yandex-react-burger/commit/32eee44d9c32a25c69e11c2b36fb55271ec64085

2022-01-30 17:02 UTC, tachkovsa commented on src/components/burger-constructor/burger-constructor.tsx
>      const [bottomBun, setBottomBun] = useState<any>(undefined);
Исправлено в https://github.com/tachkovsa/yandex-react-burger/commit/c29864b80e1fe4a64091d45416f2f34fed4bfa8a

2022-01-30 17:27 UTC, tachkovsa commented on src/components/burger-ingredients/burger-ingredients.tsx
> +            {modalVisible && toggledIngredient && (
Исправлено в https://github.com/tachkovsa/yandex-react-burger/commit/cb966a62a115815af76c17bb8fdb709fa2c01dd4

2022-01-30 17:27 UTC, tachkovsa commented on src/components/burger-constructor/burger-constructor.tsx
> +            {modalVisible && orderNumber && (
Исправлено в https://github.com/tachkovsa/yandex-react-burger/commit/cb966a62a115815af76c17bb8fdb709fa2c01dd4

2022-01-31 13:31 UTC, batr94 approved these changes
Здравствуйте! Отличная работа, Вы исправили все замечания с прошлой проверки. Ваша работа принята!

Желаю успехов в дальнейшем обучении!

2022-01-31 16:09 UTC, merged